using System.Text;
using DragonCAD.Fabrication.Outputs;

namespace DragonCAD.Fabrication.Packages;

public sealed record ManufacturingPackageArtifactSource
{
    private ManufacturingPackageArtifactSource(
        ManufacturingPackageArtifactKind kind,
        ManufacturingRelativePath relativePath,
        byte[] content)
    {
        Kind = kind;
        RelativePath = relativePath;
        Content = content;
    }

    public ManufacturingPackageArtifactKind Kind { get; }

    public ManufacturingRelativePath RelativePath { get; }

    public IReadOnlyList<byte> Content { get; }

    public static ManufacturingPackageArtifactSource Create(
        ManufacturingPackageArtifactKind kind,
        string relativePath,
        string content)
    {
        ArgumentNullException.ThrowIfNull(content);

        return Create(kind, ManufacturingRelativePath.Create(relativePath), Encoding.UTF8.GetBytes(content));
    }

    public static ManufacturingPackageArtifactSource Create(
        ManufacturingPackageArtifactKind kind,
        ManufacturingRelativePath relativePath,
        IReadOnlyCollection<byte> content)
    {
        ArgumentNullException.ThrowIfNull(relativePath);
        ArgumentNullException.ThrowIfNull(content);

        if (kind == ManufacturingPackageArtifactKind.Manifest)
        {
            throw new ArgumentException("Manufacturing package manifest artifacts are generated by the bundle builder.", nameof(kind));
        }

        return new ManufacturingPackageArtifactSource(kind, relativePath, content.ToArray());
    }
}
